virtualpkg=NetworkManager:NetworkManager-dinit
virtualpkg=chrony:chrony-dinit
virtualpkg=dbus:dbus-dinit
virtualpkg=dhcpcd:dhcpcd-dinit
virtualpkg=elogind:elogind-dinit
virtualpkg=libvirt:libvirt-dinit
virtualpkg=lightdm:lightdm-dinit
virtualpkg=ly:ly-dinit
virtualpkg=openssh:openssh-dinit
virtualpkg=polkit:polkit-dinit
virtualpkg=sddm:sddm-dinit
virtualpkg=wpa_supplicant:wpa_supplicant-dinit
